name: $bog_quiz Desktop

permissions: write-all

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: macos-latest
            target: desktop
          - platform: ubuntu-latest
            target: desktop
          - platform: windows-latest
            target: desktop
          - platform: ubuntu-latest
            target: android

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: hyoo-ru/mam_build@master2
        with:
          package: 'bog/quiz'

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: dtolnay/rust-toolchain@stable

      - name: Install Linux dependencies
        if: matrix.platform == 'ubuntu-latest' && matrix.target == 'desktop'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Setup Android
        if: matrix.target == 'android'
        uses: android-actions/setup-android@v3

      - name: Setup Android NDK
        if: matrix.target == 'android'
        run: sdkmanager "ndk;27.0.12077973"

      - name: Install Tauri CLI
        run: npm install --save-dev @tauri-apps/cli

      - name: Init mobile
        if: matrix.target != 'desktop'
        working-directory: bog/quiz
        run: npx tauri ${{ matrix.target }} init

      - name: Build
        working-directory: bog/quiz
        run: npx tauri ${{ matrix.target == 'desktop' && 'build' || format('{0} build', matrix.target) }}

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform }}-${{ matrix.target }}
          path: bog/quiz/src-tauri/${{ matrix.target == 'desktop' && 'target/release/bundle/' || format('gen/{0}/build/', matrix.target) }}

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/**/*
          generate_release_notes: true
